ALTER TYPE "FormaPagamentoDespesa" ADD VALUE IF NOT EXISTS 'CARTAO_DEBITO';
ALTER TYPE "FormaPagamentoDespesa" ADD VALUE IF NOT EXISTS 'VALE_ALIMENTACAO';
ALTER TYPE "FormaPagamentoDespesa" ADD VALUE IF NOT EXISTS 'VALE_REFEICAO';
ALTER TYPE "FormaPagamentoDespesa" ADD VALUE IF NOT EXISTS 'BOLETO';
